name: Build and push Docker image on release-publish
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1    
      - name: Build, tag, and push docker image to Amazon ECR
        id: build-tag-push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          VERSION_TAG: ${{ github.event.tag_name }}
        run: |
          echo $REGISTRY
          echo $GITHUB_SHA
          echo $VERSION_TAG
          echo $GITHUB_REF_NAME
          
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.tag_name }}
